name: Code Analysis

on:
    push:
        branches:
            - main
            - next
        paths:
            - "packages/**"
            - "lib/**"
    pull_request:
        branches:
            - main
            - next
        paths:
            - "packages/**"
            - "lib/**"
    workflow_dispatch:

jobs:
    dart-analyze:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: npm

            - uses: subosito/flutter-action@v2
              with:
                  channel: beta
                  cache: true

            - name: 🚧 Do prerequisites
              run: |
                  npm ci
                  (cd packages/shared; dart pub get)
                  (cd packages/anilist; dart pub get)
                  (cd packages/discord_rpc; dart pub get)
                  flutter pub get
                  dart run cli/prerequisites.dart

            - name: 🩺 Code Analysis
              run: dart run cli/code_analysis.dart
